### PR TITLE
parse-mf2: read whole contents of STDIN

### PR DESCRIPTION
**Pull request by martymcguire**
[`fgets(STDIN)` reads only one line](https://www.php.net/manual/en/function.fgets.php), but we want to pass a string containing the whole contents of the input to `Mf2\parse`.

### CODE REVIEW

**Comment by gRegorLove** [comment]
@martymcguire I just merged https://github.com/microformats/php-mf2/pull/217 which fixes the failing tests here. Can you rebase on master? Sorry for the inconvenience.

**Comment by martymcguire** [comment]
@gRegorLove thanks! rebased and force-pushed. fingers crossed travis likes it now.

**Comment by gRegorLove** [comment]
🙌🏻

**Comment by martymcguire** [comment]
just need someone w/ merge permission! 😅

**Pull request merged**
