### PR TITLE
Test enhancement

### PR DESCRIPTION
**Pull request by peter279k**
# Changed log
- Update PHPUnit version to be `^4.8.36` to prepare for latest stable PHP version.
- Using the c;ass-based PHPUnit namespace.
- Using the `psr-4` to load the required classes automatically.
- According to the [PHPUnit fixtures reference](https://phpunit.readthedocs.io/en/latest/fixtures.html?highlight=fixtures), the `setUp` method should be `protected`, not `public`.

### CODE REVIEW

**Comment by Lewiscowles1986** [comment]
I feel like if this were updated and the bump to PHPUnit 5 made separately, it would help avoid dual changes in a single PR. @peter279k has contributed to other PHP projects and I have found them a pleasure to work with,

This already has conflicts, so should hold off on rebase until @Zegnat work merges, at which point some of this I think may become redundant or need fresh approach.

Could be multiple PR's in this as right now it is changing a lot.

**Comment by Zegnat** [comment]
Yikes, this issue somehow ended up way long down my review list. Apologies @peter279k!

I think what we want to do now that php-mf2 has moved to being PHP 5.6+ is to completely update PHP Unit to something like:

```diff
-         "phpunit/phpunit": "4.8.*",
+        "phpunit/phpunit": "^5.0 || ^8.0",
```

If possible for our test cases, that is.

PHPUnit 5 has long fallen out of support but was the last version to officially run on PHP 5.6. PHPUnit 8 is still supported until 2021 and runs on PHP 7.2 to PHP 7.4. Older versions pre PHP 7.2 can use PHPUnit 5. (Information per [PHPUnit's Supported Versions page](https://phpunit.de/supported-versions.html)).

This probably also enables some of the class based changes to the tests. As we are able to completely leave PHPUnit 4 behind.

What do you think @peter279k? Is that a change you would like to work on in this PR, or should we see if someone else wants to pick it up?

For those who work on other projects that support PHP 5.6, like @dshanske, any advice on how tests are usually set up to test such a wide span of PHP versions?

**Comment by peter279k** [comment]
> Yikes, this issue somehow ended up way long down my review list. Apologies @peter279k!
> 
> I think what we want to do now that php-mf2 has moved to being PHP 5.6+ is to completely update PHP Unit to something like:
> 
> ```diff
> -         "phpunit/phpunit": "4.8.*",
> +        "phpunit/phpunit": "^5.0 || ^8.0",
> ```
> 
> If possible for our test cases, that is.
> 
> PHPUnit 5 has long fallen out of support but was the last version to officially run on PHP 5.6. PHPUnit 8 is still supported until 2021 and runs on PHP 7.2 to PHP 7.4. Older versions pre PHP 7.2 can use PHPUnit 5. (Information per [PHPUnit's Supported Versions page](https://phpunit.de/supported-versions.html)).
> 
> This probably also enables some of the class based changes to the tests. As we are able to completely leave PHPUnit 4 behind.
> 
> What do you think @peter279k? Is that a change you would like to work on in this PR, or should we see if someone else wants to pick it up?
> 
> For those who work on other projects that support PHP 5.6, like @dshanske, any advice on how tests are usually set up to test such a wide span of PHP versions?

Thanks for your reply.

I will do that at my available time.

**Comment by Lewiscowles1986** [comment]
@peter279k I have some experience with using yoast polyfill so that PHPunit is brought in via indirection. Do you think that could help with this? Do you have experience of this? Should this be closed?

@Zegnat not sure if above applies to you too?

Happy to make a new patch request if that seems preferable?

**Comment by peter279k** [comment]
I almost forgot this PR. It's outdated and there're many conflict in this PR.

I will close the PR. Please feel free to create new PR for that, @Lewiscowles1986.

And we can find what the proper way is for this test improvements.

**Pull request closed without merging**
